name: test build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-2025, macos-latest]
        arch: [x86, x64]  
        build_type: [Release]
        
    steps:
    - uses: actions/checkout@v4

    # Cache build artifacts (CMake and compiler intermediate files)
    - name: Cache build directory
      uses: actions/cache@v4
      with:
        path: build
        key: ${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-cmake-

    - name: Install LLVM on macOS
      if: runner.os == 'macOS'
      run: |
        brew install llvm

    - name: Configure environment to use Homebrew LLVM
      if: runner.os == 'macOS'
      run: |
        echo "CC=/opt/homebrew/opt/llvm/bin/clang" >> $GITHUB_ENV
        echo "CXX=/opt/homebrew/opt/llvm/bin/clang++" >> $GITHUB_ENV

    - name: Install dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get upgrade

        sudo apt-get install -y build-essential git make pkg-config cmake ninja-build gnome-desktop-testing libasound2-dev libpulse-dev libaudio-dev libjack-dev libsndio-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev --fix-missing

    - name: Build
      run: |
        python build.py
